name: Update Workflow Name

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Chose environment'
        required: true
        type: choice
        options:
          - n1
          - n2
          - n3
        default: 'n1'
      repo:
        description: 'Chose repo'
        required: true
        type: choice
        options:
          - be
          - fe
        default: 'be'

jobs:
  update_workflow:
    name: Build and put image ${{github.event.inputs.environment.options}} ${{github.event.inputs.environment.repo}}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Verify file exists
      run: ls -al .github/workflows

    - name: Update workflow name
      run: |
        sed -i 's/^name: .*/name: '"${{ github.event.inputs.new_name }}"'/' .github/workflows/main.yml

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add .github/workflows/main.yml
        git commit -m "Update workflow name to ${{ github.event.inputs.new_name }}"
        git push
