name: Update Workflow Name

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Chose environment'
        required: true
        type: choice
        options:
          - n1
          - n2
          - n3
        default: 'n1'
      repo:
        description: 'Chose repo'
        required: true
        type: choice
        options:
          - be
          - fe
        default: 'be'

jobs:
  update_workflow:
    name: ${{github.event.inputs.environment.options}} ${{github.event.inputs.environment.repo}}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      run: echo "${{github.event.inputs.environment.options}} ${{github.event.inputs.environment.repo}}""
